spring:
  datasource:
    url: jdbc:mysql://counter.ccuqofgdcmrb.ap-northeast-1.rds.amazonaws.com:3306/hrm?createDatabaseIfNotExist=true
    username: admin
    password: counter!234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect:
          storage_engine: innodb
#  ldap:
#    urls: ldap://ldap.abacussw.co.kr:389/
#    base: dc=abacussw,dc=co,dc=kr
#    username: uid=root,cn=users,dc=abacussw,dc=co,dc=kr
#    password: Abacus10!@
#    user:
#      dn:
#        pattern: uid={0}
#  ldap:
#    embedded:
#      ldif: classpath:test-server.ldif
#      base-dn: dc=springframework,dc=org
#      port: 8389
  ldap:
    urls: ldap://ldap.abacussw.co.kr:389/
    username: uid=root,cn=users,dc=abacussw,dc=co,dc=kr
    password: Abacus10!@
    base: dc=abacussw,dc=co,dc=kr
    user:
      dn:
        pattern: uid={0},cn=users,dc=abacussw,dc=co,dc=kr


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
module:
  logging:
    dir: C://dev/hrm-log
    level: INFO
springdoc:
  packages-to-scan: kr.co.hrm
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: hrm api swagger
  version: v1.0.0
  description: hrm project description
  cache:
    disabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
