spring:
  datasource:
    url: jdbc:mysql://counter.ccuqofgdcmrb.ap-northeast-1.rds.amazonaws.com:3306/hrm?createDatabaseIfNotExist=true
    username: admin
    password: counter!234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        show_sql: true
        dialect:
          storage_engine: innodb
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
module:
  logging:
    dir: C://dev/hrm-log
    level: INFO
